# playbook.yml
- name: Apply Kubernetes manifests
  hosts: localhost
  tasks:
    - name: Apply deployment manifest
      command: kubectl apply -f deployment.yaml

    - name: Apply service manifest
      command: kubectl apply -f service.yaml
