# deploy.yml
- name: Deploy Kubernetes Resources
  hosts: localhost
  tasks:
    - name: Ensure kubectl is available
      command: kubectl version --client
      register: kubectl_check
      ignore_errors: true

    - name: Install kubectl if not present
      apt:
        name: kubectl
        state: present
      when: kubectl_check.rc != 0

    - name: Apply deployment manifest
      command: kubectl apply -f deployment.yaml
      args:
        chdir: /var/lib/jenkins/spe

    - name: Apply service manifest
      command: kubectl apply -f service.yaml
      args:
        chdir: /var/lib/jenkins/spe

    - name: Wait for deployment to be ready
      command: kubectl wait --for=condition=available deployment/pwapp-deployment --timeout=360s
      args:
        chdir: /var/lib/jenkins/spe

    - name: Ensure service is running
      command: kubectl get service pwapp-service
      register: service_check

    - name: Fail if service is not running
      fail:
        msg: "pwapp-service is not running"
      when: service_check.rc != 0
