apiVersion: v1
kind: Service
metadata:
  name: pwapp-service
spec:
  selector:
    app: pwapp
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: LoadBalancer  # Use 'LoadBalancer' if you want to expose the service externally
